export const DELETE_IGREDIENT: "DELETE_IGREDIENT" = "DELETE_IGREDIENT";
export const DROP_INGREDIENT: "DROP_INGREDIENT" = "DROP_INGREDIENT";
export const GET_ORDER_NUMBER_SUCCESS: "GET_ORDER_NUMBER_SUCCESS" =
  "GET_ORDER_NUMBER_SUCCESS";
export const REORDER_CONSTRUCTOR_ITEM: "REORDER_CONSTRUCTOR_ITEM" =
  "REORDER_CONSTRUCTOR_ITEM";
export const GET_CONSTRUCTOR_INGREDIENTS: "GET_CONSTRUCTOR_INGREDIENTS" =
  "GET_CONSTRUCTOR_INGREDIENTS";
