export const WS_CONNECTION_INIT = "WS_CONNECTION_INIT";
export const WS_SEND_MESSAGE = "WS_SEND_MESSAGE";
export const WS_CONNECTION_CLOSE = "WS_CONNECTION_CLOSE";

export const FEED_WS_CONNECTION_START = "FEED_WS_CONNECTION_START";
export const FEED_WS_CONNECTION_SUCCESS = "FEED_WS_CONNECTION_SUCCESS";
export const FEED_WS_CONNECTION_ERROR = "FEED_WS_CONNECTION_ERROR";
export const FEED_WS_CONNECTION_CLOSED = "FEED_WS_CONNECTION_CLOSED";
export const FEED_WS_GET_MESSAGE = "FEED_WS_GET_MESSAGE";

export const PROFILE_FEED_WS_CONNECTION_START =
  "PROFILE_FEED_WS_CONNECTION_START";
export const PROFILE_FEED_WS_CONNECTION_SUCCESS =
  "PROFILE_FEED_WS_CONNECTION_SUCCESS";
export const PROFILE_FEED_WS_CONNECTION_ERROR =
  "PROFILE_FEED_WS_CONNECTION_ERROR";
export const PROFILE_FEED_WS_CONNECTION_CLOSED =
  "PROFILE_FEED_WS_CONNECTION_CLOSED";
export const PROFILE_FEED_WS_GET_MESSAGE = "PROFILE_FEED_WS_GET_MESSAGE";
